/* ----------------------------------------------------------------------------
 * iocpStubInit.c --
 *
 *	This file contains the initializers for the Iocpsock stub vectors.
 *
 * ----------------------------------------------------------------------------
 * RCS: @(#) $Id$
 * ----------------------------------------------------------------------------
 */

#include "iocpsockInt.h"

/*
 * WARNING: The contents of this file are automatically generated by the
 * $(ROOT)/tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the iocpsock.decls script.
 */

/* !BEGIN!: Do not edit below this line. */


/* !END!: Do not edit above this line. */
