/* ----------------------------------------------------------------------------
 * iocpStubInit.c --
 *
 *	This file contains the initializers for the Iocpsock stub vectors.
 *
 * ----------------------------------------------------------------------------
 * RCS: @(#) $Id$
 * ----------------------------------------------------------------------------
 */

#include "iocpsockInt.h"

/*
 * WARNING: The contents of this file are automatically generated by the
 * $(ROOT)/tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the iocpsock.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

IocpIntStubs iocpIntStubs = {
    TCL_STUB_MAGIC,
    NULL,
};

static IocpStubHooks iocpStubHooks = {
    &iocpIntStubs
};

IocpStubs iocpStubs = {
    TCL_STUB_MAGIC,
    &iocpStubHooks,
    Iocpsock_Init, /* 0 */
    Iocpsock_SafeInit, /* 1 */
    Iocp_OpenTcpClient, /* 2 */
    Iocp_OpenTcpServer, /* 3 */
    Iocp_OpenUdpSocket, /* 4 */
    Iocp_OpenIrdaClient, /* 5 */
    Iocp_OpenIrdaServer, /* 6 */
};

/* !END!: Do not edit above this line. */
